user1 = User.create!( {email: 'friend@email.com', password: 'password' })
user2 = User.create!( {email: 'pal@email.com', password: 'password'} )
user3 = User.create!( {email: 'buddy@email.com', password: 'password'} )
user4 = User.create!( {email: 'amigo@email.com', password: 'password'} )
user5 = User.create!( {email: 'chum@email.com', password: 'password'} )
user6 = User.create!( {email: 'bestie@email.com', password: 'password'} )
user7 = User.create!( {email: 'bruv@email.com', password: 'password'} )
user8 = User.create!( {email: 'companion@email.com', password: 'password'} )

user1.add_friend(user2)
user1.add_friend(user3)
user1.add_friend(user4)
user1.add_friend(user5)
user1.add_friend(user6)
user1.add_friend(user7)
user1.add_friend(user8)
user2.add_friend(user3)
user2.add_friend(user4)
user2.add_friend(user5)
user2.add_friend(user6)
user2.add_friend(user7)
user2.add_friend(user8)
user3.add_friend(user4)
user3.add_friend(user5)
user3.add_friend(user6)
user3.add_friend(user7)
user3.add_friend(user8)
user4.add_friend(user5)
user4.add_friend(user6)
user4.add_friend(user7)
user4.add_friend(user8)
user5.add_friend(user6)
user5.add_friend(user7)
user5.add_friend(user8)
user6.add_friend(user7)
user7.add_friend(user8)
